<html>
<body>
<table boeder="1"><tr><th>Mattapan Station&nbsp;</th><th >River St Opp Cedar St&nbsp;</th><th>Dorchester Ave Opp Adirondack Pl&nbsp;</th><th >Dorchester Ave & Gallivan Blvd&nbsp;</th><th>Dorchester Ave & Ashmont Busway&nbsp;</th><th >Park St Busway & Dorchester Ave&nbsp;</th><th>Fields Corner Station & Red Line&nbsp;</th><th >Ashmont Station&nbsp;</th><th>Geneva Ave Opp Vinson St&nbsp;</th><th >Bowdoin St & Geneva Ave&nbsp;</th><th>St Peters Sq & Church&nbsp;</th><th >Hancock St & Bowdoin St&nbsp;</th><th>Columbia Rd & Hancock St&nbsp;</th><th >Dudley Station&nbsp;</th><th>Washington St & Massachusetts Ave&nbsp;</th><th >Washington St & E Berkeley St&nbsp;</th><th>Haymarket Station&nbsp;</th><th >Dudley St & Magazine St&nbsp;</th><th>Dudley Station&nbsp;</th><th >Malcolm X Blvd & Tremont St&nbsp;</th><th>Ruggles Sta&nbsp;</th></tr><tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:26 AM</td><td>03:32 AM</td><td >03:35 AM</td><td></td><td >03:38 AM</td><td>03:40 AM</td><td ></td><td></td><td ></td><td></td><td >03:43 AM</td><td>03:46 AM</td><td ></td><td></td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:56 AM</td><td>04:02 AM</td><td >04:05 AM</td><td></td><td >04:08 AM</td><td>04:10 AM</td><td ></td><td></td><td ></td><td></td><td >04:13 AM</td><td>04:16 AM</td><td ></td><td></td></tr>
<tr><td>04:28 AM</td><td >04:32 AM</td><td>04:34 AM</td><td >04:36 AM</td><td>04:38 AM</td><td >04:42 AM</td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>04:49 AM</td><td >04:55 AM</td><td>04:58 AM</td><td >05:02 AM</td><td>05:08 AM</td><td ></td><td></td><td ></td><td></td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:11 AM</td><td>05:12 AM</td><td ></td><td></td><td ></td><td></td><td >05:16 AM</td><td>05:19 AM</td><td >05:21 AM</td><td>05:23 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:25 AM</td><td>05:26 AM</td><td ></td><td></td><td ></td><td></td><td >05:30 AM</td><td>05:33 AM</td><td >05:35 AM</td><td>05:37 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:40 AM</td><td>05:41 AM</td><td ></td><td></td><td ></td><td></td><td >05:45 AM</td><td>05:48 AM</td><td >05:50 AM</td><td>05:52 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:55 AM</td><td>05:56 AM</td><td ></td><td></td><td ></td><td></td><td >06:01 AM</td><td>06:05 AM</td><td >06:09 AM</td><td>06:12 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:05 AM</td><td>06:06 AM</td><td ></td><td></td><td ></td><td></td><td >06:12 AM</td><td>06:16 AM</td><td >06:20 AM</td><td>06:23 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:15 AM</td><td>06:16 AM</td><td ></td><td></td><td ></td><td></td><td >06:22 AM</td><td>06:26 AM</td><td >06:30 AM</td><td>06:33 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:25 AM</td><td>06:26 AM</td><td ></td><td></td><td ></td><td></td><td >06:32 AM</td><td>06:36 AM</td><td >06:40 AM</td><td>06:43 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:29 AM</td><td>06:30 AM</td><td ></td><td></td><td ></td><td></td><td >06:36 AM</td><td>06:40 AM</td><td >06:44 AM</td><td>06:47 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:33 AM</td><td>06:34 AM</td><td ></td><td></td><td ></td><td></td><td >06:40 AM</td><td>06:44 AM</td><td >06:48 AM</td><td>06:51 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:37 AM</td><td>06:38 AM</td><td ></td><td></td><td ></td><td></td><td >06:44 AM</td><td>06:48 AM</td><td >06:52 AM</td><td>06:55 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:41 AM</td><td>06:42 AM</td><td ></td><td></td><td ></td><td></td><td >06:48 AM</td><td>06:52 AM</td><td >06:56 AM</td><td>06:59 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:44 AM</td><td>06:48 AM</td><td ></td><td></td><td ></td><td></td><td >06:52 AM</td><td>06:57 AM</td><td ></td><td></td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:47 AM</td><td>06:51 AM</td><td ></td><td></td><td ></td><td></td><td >06:55 AM</td><td>07:00 AM</td><td ></td><td></td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:49 AM</td><td>06:50 AM</td><td ></td><td></td><td ></td><td></td><td >06:56 AM</td><td>07:00 AM</td><td >07:04 AM</td><td>07:08 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>06:46 AM</td><td ></td><td></td><td >06:49 AM</td><td></td><td >06:53 AM</td><td>06:55 AM</td><td ></td><td></td><td ></td><td></td><td >07:01 AM</td><td>07:06 AM</td><td >07:10 AM</td><td>07:14 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:55 AM</td><td>06:56 AM</td><td ></td><td></td><td ></td><td></td><td >07:02 AM</td><td>07:07 AM</td><td >07:11 AM</td><td>07:15 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:58 AM</td><td>07:02 AM</td><td ></td><td></td><td ></td><td></td><td >07:07 AM</td><td>07:12 AM</td><td ></td><td></td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:00 AM</td><td>07:01 AM</td><td ></td><td></td><td ></td><td></td><td >07:07 AM</td><td>07:12 AM</td><td >07:16 AM</td><td>07:20 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:04 AM</td><td>07:05 AM</td><td ></td><td></td><td ></td><td></td><td >07:11 AM</td><td>07:16 AM</td><td >07:20 AM</td><td>07:24 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:10 AM</td><td>07:11 AM</td><td ></td><td></td><td ></td><td></td><td >07:17 AM</td><td>07:22 AM</td><td >07:26 AM</td><td>07:30 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:15 AM</td><td>07:16 AM</td><td ></td><td></td><td ></td><td></td><td >07:22 AM</td><td>07:27 AM</td><td >07:31 AM</td><td>07:35 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:20 AM</td><td>07:21 AM</td><td ></td><td></td><td ></td><td></td><td >07:27 AM</td><td>07:32 AM</td><td >07:36 AM</td><td>07:40 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:25 AM</td><td>07:26 AM</td><td ></td><td></td><td ></td><td></td><td >07:32 AM</td><td>07:37 AM</td><td >07:41 AM</td><td>07:45 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:31 AM</td><td>07:32 AM</td><td ></td><td></td><td ></td><td></td><td >07:38 AM</td><td>07:43 AM</td><td >07:47 AM</td><td>07:51 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:37 AM</td><td>07:38 AM</td><td ></td><td></td><td ></td><td></td><td >07:44 AM</td><td>07:49 AM</td><td >07:53 AM</td><td>07:57 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:43 AM</td><td>07:44 AM</td><td ></td><td></td><td ></td><td></td><td >07:50 AM</td><td>07:55 AM</td><td >07:59 AM</td><td>08:03 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:49 AM</td><td>07:50 AM</td><td ></td><td></td><td ></td><td></td><td >07:56 AM</td><td>08:01 AM</td><td >08:05 AM</td><td>08:09 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:55 AM</td><td>07:56 AM</td><td ></td><td></td><td ></td><td></td><td >08:02 AM</td><td>08:07 AM</td><td >08:11 AM</td><td>08:15 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:01 AM</td><td>08:02 AM</td><td ></td><td></td><td ></td><td></td><td >08:08 AM</td><td>08:13 AM</td><td >08:17 AM</td><td>08:21 AM</td></tr>
<tr><td></td><td ></td><td></td><td >/td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:07 AM</td><td>08:08 AM</td><td ></td><td></td><td ></td><td></td><td >08:14 AM</td><td>08:19 AM</td><td >08:23 AM</td><td>08:27 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:13 AM</td><td>08:14 AM</td><td ></td><td></td><td ></td><td></td><td >08:20 AM</td><td>08:25 AM</td><td >08:29 AM</td><td>08:33 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:19 AM</td><td>08:20 AM</td><td ></td><td></td><td ></td><td></td><td >08:26 AM</td><td>08:31 AM</td><td >08:35 AM</td><td>08:39 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:25 AM</td><td>08:26 AM</td><td ></td><td></td><td ></td><td></td><td >08:32 AM</td><td>08:37 AM</td><td >08:41 AM</td><td>08:45 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:32 AM</td><td>08:33 AM</td><td ></td><td></td><td ></td><td></td><td >08:39 AM</td><td>08:44 AM</td><td >08:48 AM</td><td>08:52 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:40 AM</td><td>08:41 AM</td><td ></td><td></td><td ></td><td></td><td >08:47 AM</td><td>08:52 AM</td><td >08:56 AM</td><td>09:00 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >08:50 AM</td><td>08:51 AM</td><td ></td><td></td><td ></td><td></td><td >08:57 AM</td><td>09:02 AM</td><td >09:06 AM</td><td>09:10 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >09:00 AM</td><td>09:01 AM</td><td ></td><td></td><td ></td><td></td><td >09:07 AM</td><td>09:12 AM</td><td >09:16 AM</td><td>09:20 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >09:12 AM</td><td>09:13 AM</td><td ></td><td></td><td ></td><td></td><td >09:19 AM</td><td>09:24 AM</td><td >09:28 AM</td><td>09:32 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >09:24 AM</td><td>09:25 AM</td><td ></td><td></td><td ></td><td></td><td >09:31 AM</td><td>09:36 AM</td><td >09:40 AM</td><td>09:44 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >09:36 AM</td><td>09:37 AM</td><td ></td><td></td><td ></td><td></td><td >09:43 AM</td><td>09:48 AM</td><td >09:52 AM</td><td>09:56 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>09:51 AM</td><td >09:52 AM</td><td>09:53 AM</td><td ></td><td></td><td ></td><td></td><td >09:59 AM</td><td>10:03 AM</td><td >10:06 AM</td><td>10:10 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>10:07 AM</td><td >10:08 AM</td><td>10:11 AM</td><td ></td><td></td><td ></td><td></td><td >10:16 AM</td><td>10:20 AM</td><td >10:23 AM</td><td>10:27 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>10:23 AM</td><td >10:24 AM</td><td>10:27 AM</td><td ></td><td></td><td ></td><td></td><td >10:32 AM</td><td>10:36 AM</td><td >10:39 AM</td><td>10:43 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>10:39 AM</td><td >10:40 AM</td><td>10:43 AM</td><td ></td><td></td><td ></td><td></td><td >10:48 AM</td><td>10:52 AM</td><td >10:55 AM</td><td>10:59 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>10:55 AM</td><td >10:56 AM</td><td>10:59 AM</td><td ></td><td></td><td ></td><td></td><td >11:07 AM</td><td>11:12 AM</td><td >11:17 AM</td><td>11:21 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>11:11 AM</td><td >11:12 AM</td><td>11:15 AM</td><td ></td><td></td><td ></td><td></td><td >11:23 AM</td><td>11:28 AM</td><td >11:33 AM</td><td>11:37 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>11:27 AM</td><td >11:28 AM</td><td>11:31 AM</td><td ></td><td></td><td ></td><td></td><td >11:39 AM</td><td>11:44 AM</td><td >11:49 AM</td><td>11:53 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>11:43 AM</td><td >11:44 AM</td><td>11:47 AM</td><td ></td><td></td><td ></td><td></td><td >11:55 AM</td><td>12:00 PM</td><td >12:05 PM</td><td>12:09 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>12:00 PM</td><td >12:01 PM</td><td>12:04 PM</td><td ></td><td></td><td ></td><td></td><td >12:12 PM</td><td>12:17 PM</td><td >12:22 PM</td><td>12:26 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>12:17 PM</td><td >12:18 PM</td><td>12:21 PM</td><td ></td><td></td><td ></td><td></td><td >12:29 PM</td><td>12:34 PM</td><td >12:39 PM</td><td>12:43 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>12:34 PM</td><td >12:35 PM</td><td>12:38 PM</td><td ></td><td></td><td ></td><td></td><td >12:46 PM</td><td>12:51 PM</td><td >12:56 PM</td><td>01:00 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>12:51 PM</td><td >12:52 PM</td><td>12:55 PM</td><td ></td><td></td><td ></td><td></td><td >01:03 PM</td><td>01:08 PM</td><td >01:13 PM</td><td>01:17 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>01:08 PM</td><td >01:09 PM</td><td>01:12 PM</td><td ></td><td></td><td ></td><td></td><td >01:20 PM</td><td>01:25 PM</td><td >01:30 PM</td><td>01:34 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>01:25 PM</td><td >01:26 PM</td><td>01:29 PM</td><td ></td><td></td><td ></td><td></td><td >01:37 PM</td><td>01:42 PM</td><td >01:47 PM</td><td>01:51 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>01:42 PM</td><td >01:43 PM</td><td>01:46 PM</td><td ></td><td></td><td ></td><td></td><td >01:54 PM</td><td>01:59 PM</td><td >02:04 PM</td><td>02:08 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>01:53 PM</td><td >01:54 PM</td><td>01:57 PM</td><td ></td><td></td><td ></td><td></td><td >02:05 PM</td><td>02:10 PM</td><td >02:15 PM</td><td>02:19 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>02:04 PM</td><td >02:05 PM</td><td>02:08 PM</td><td ></td><td></td><td ></td><td></td><td >02:16 PM</td><td>02:21 PM</td><td >02:26 PM</td><td>02:30 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >02:15 PM</td><td>02:19 PM</td><td ></td><td></td><td ></td><td></td><td >02:24 PM</td><td>02:29 PM</td><td ></td><td></td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>02:15 PM</td><td >02:16 PM</td><td>02:19 PM</td><td ></td><td></td><td ></td><td></td><td >02:27 PM</td><td>02:32 PM</td><td >02:37 PM</td><td>02:41 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>02:26 PM</td><td >02:27 PM</td><td>02:30 PM</td><td ></td><td></td><td ></td><td></td><td >02:38 PM</td><td>02:43 PM</td><td >02:48 PM</td><td>02:52 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>02:37 PM</td><td >02:38 PM</td><td>02:41 PM</td><td ></td><td></td><td ></td><td></td><td >02:49 PM</td><td>02:54 PM</td><td >02:59 PM</td><td>03:03 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>02:48 PM</td><td >02:49 PM</td><td>02:52 PM</td><td ></td><td></td><td ></td><td></td><td >03:00 PM</td><td>03:05 PM</td><td >03:10 PM</td><td>03:14 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>02:57 PM</td><td >02:58 PM</td><td>03:00 PM</td><td ></td><td></td><td ></td><td></td><td >03:07 PM</td><td>03:12 PM</td><td >03:17 PM</td><td>03:21 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:04 PM</td><td>03:05 PM</td><td ></td><td></td><td ></td><td></td><td >03:12 PM</td><td>03:17 PM</td><td >03:22 PM</td><td>03:26 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:13 PM</td><td>03:14 PM</td><td ></td><td></td><td ></td><td></td><td >03:21 PM</td><td>03:26 PM</td><td >03:31 PM</td><td>03:35 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:22 PM</td><td>03:23 PM</td><td ></td><td></td><td ></td><td></td><td >03:30 PM</td><td>03:35 PM</td><td >03:40 PM</td><td>03:44 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:26 PM</td><td>03:30 PM</td><td ></td><td></td><td ></td><td></td><td >03:35 PM</td><td>03:40 PM</td><td ></td><td></td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:31 PM</td><td>03:32 PM</td><td ></td><td></td><td ></td><td></td><td >03:39 PM</td><td>03:44 PM</td><td >03:49 PM</td><td>03:53 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:40 PM</td><td>03:41 PM</td><td ></td><td></td><td ></td><td></td><td >03:48 PM</td><td>03:53 PM</td><td >03:58 PM</td><td>04:02 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:49 PM</td><td>03:50 PM</td><td ></td><td></td><td ></td><td></td><td >03:57 PM</td><td>04:02 PM</td><td >04:07 PM</td><td>04:11 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >03:58 PM</td><td>03:59 PM</td><td ></td><td></td><td ></td><td></td><td >04:06 PM</td><td>04:11 PM</td><td >04:16 PM</td><td>04:20 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >04:07 PM</td><td>04:08 PM</td><td ></td><td></td><td ></td><td></td><td >04:15 PM</td><td>04:20 PM</td><td >04:25 PM</td><td>04:29 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >04:16 PM</td><td>04:17 PM</td><td ></td><td></td><td ></td><td></td><td >04:24 PM</td><td>04:29 PM</td><td >04:34 PM</td><td>04:38 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >04:25 PM</td><td>04:26 PM</td><td ></td><td></td><td ></td><td></td><td >04:33 PM</td><td>04:38 PM</td><td >04:43 PM</td><td>04:47 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >04:34 PM</td><td>04:35 PM</td><td ></td><td></td><td ></td><td></td><td >04:42 PM</td><td>04:47 PM</td><td >04:52 PM</td><td>04:56 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >04:43 PM</td><td>04:44 PM</td><td ></td><td></td><td ></td><td></td><td >04:51 PM</td><td>04:56 PM</td><td >05:01 PM</td><td>05:05 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >04:52 PM</td><td>04:53 PM</td><td ></td><td></td><td ></td><td></td><td >05:00 PM</td><td>05:05 PM</td><td >05:10 PM</td><td>05:14 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:01 PM</td><td>05:02 PM</td><td ></td><td></td><td ></td><td></td><td >05:09 PM</td><td>05:14 PM</td><td >05:19 PM</td><td>05:23 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:10 PM</td><td>05:11 PM</td><td ></td><td></td><td ></td><td></td><td >05:18 PM</td><td>05:23 PM</td><td >05:28 PM</td><td>05:32 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:19 PM</td><td>05:20 PM</td><td ></td><td></td><td ></td><td></td><td >05:27 PM</td><td>05:32 PM</td><td >05:37 PM</td><td>05:41 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:28 PM</td><td>05:29 PM</td><td ></td><td></td><td ></td><td></td><td >05:36 PM</td><td>05:41 PM</td><td >05:46 PM</td><td>05:50 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:37 PM</td><td>05:38 PM</td><td ></td><td></td><td ></td><td></td><td >05:45 PM</td><td>05:50 PM</td><td >05:55 PM</td><td>05:59 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:46 PM</td><td>05:47 PM</td><td ></td><td></td><td ></td><td></td><td >05:54 PM</td><td>05:59 PM</td><td >06:02 PM</td><td>06:04 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >05:55 PM</td><td>05:56 PM</td><td ></td><td></td><td ></td><td></td><td >06:02 PM</td><td>06:06 PM</td><td >06:09 PM</td><td>06:11 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:05 PM</td><td>06:07 PM</td><td ></td><td></td><td ></td><td></td><td >06:12 PM</td><td>06:16 PM</td><td >06:19 PM</td><td>06:21 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:15 PM</td><td>06:17 PM</td><td ></td><td></td><td ></td><td></td><td >06:22 PM</td><td>06:26 PM</td><td >06:29 PM</td><td>06:31 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:25 PM</td><td>06:27 PM</td><td ></td><td></td><td ></td><td></td><td >06:32 PM</td><td>06:36 PM</td><td >06:39 PM</td><td>06:41 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:38 PM</td><td>06:40 PM</td><td ></td><td></td><td ></td><td></td><td >06:45 PM</td><td>06:49 PM</td><td >06:52 PM</td><td>06:54 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >06:51 PM</td><td>06:53 PM</td><td ></td><td></td><td ></td><td></td><td >06:58 PM</td><td>07:02 PM</td><td >07:05 PM</td><td>07:07 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:03 PM</td><td>07:05 PM</td><td ></td><td></td><td ></td><td></td><td >07:10 PM</td><td>07:14 PM</td><td >07:17 PM</td><td>07:19 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:15 PM</td><td>07:17 PM</td><td ></td><td></td><td ></td><td></td><td >07:22 PM</td><td>07:26 PM</td><td >07:29 PM</td><td>07:31 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td ></td><td></td><td >07:25 PM</td><td>07:27 PM</td><td ></td><td></td><td ></td><td></td><td >07:32 PM</td><td>07:36 PM</td><td >07:39 PM</td><td>07:41 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>07:30 PM</td><td ></td><td></td><td >07:32 PM</td><td></td><td >07:35 PM</td><td>07:37 PM</td><td ></td><td></td><td ></td><td></td><td >07:42 PM</td><td>07:46 PM</td><td >07:49 PM</td><td>07:51 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>07:50 PM</td><td ></td><td></td><td >07:52 PM</td><td></td><td >07:55 PM</td><td>07:57 PM</td><td ></td><td></td><td ></td><td></td><td >08:02 PM</td><td>08:06 PM</td><td >08:09 PM</td><td>08:11 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>08:10 PM</td><td ></td><td></td><td >08:12 PM</td><td></td><td >08:15 PM</td><td>08:17 PM</td><td ></td><td></td><td ></td><td></td><td >08:22 PM</td><td>08:26 PM</td><td >08:29 PM</td><td>08:31 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>08:30 PM</td><td ></td><td></td><td >08:32 PM</td><td></td><td >08:35 PM</td><td>08:37 PM</td><td ></td><td></td><td ></td><td></td><td >08:42 PM</td><td>08:46 PM</td><td >08:49 PM</td><td>08:51 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>08:50 PM</td><td ></td><td></td><td >08:52 PM</td><td></td><td >08:55 PM</td><td>08:57 PM</td><td ></td><td></td><td ></td><td></td><td >09:01 PM</td><td>09:04 PM</td><td >09:07 PM</td><td>09:09 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>09:10 PM</td><td ></td><td></td><td >09:11 PM</td><td></td><td >09:14 PM</td><td>09:16 PM</td><td ></td><td></td><td ></td><td></td><td >09:20 PM</td><td>09:23 PM</td><td >09:26 PM</td><td>09:28 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>09:30 PM</td><td ></td><td></td><td >09:31 PM</td><td></td><td >09:34 PM</td><td>09:36 PM</td><td ></td><td></td><td ></td><td></td><td >09:40 PM</td><td>09:43 PM</td><td >09:46 PM</td><td>09:48 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>09:50 PM</td><td ></td><td></td><td >09:51 PM</td><td></td><td >09:54 PM</td><td>09:56 PM</td><td ></td><td></td><td ></td><td></td><td >10:00 PM</td><td>10:03 PM</td><td >10:06 PM</td><td>10:08 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>10:10 PM</td><td ></td><td></td><td >10:11 PM</td><td></td><td >10:14 PM</td><td>10:16 PM</td><td ></td><td></td><td ></td><td></td><td >10:20 PM</td><td>10:23 PM</td><td >10:26 PM</td><td>10:28 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>10:30 PM</td><td ></td><td></td><td >10:31 PM</td><td></td><td >10:34 PM</td><td>10:36 PM</td><td ></td><td></td><td ></td><td></td><td >10:40 PM</td><td>10:43 PM</td><td >10:46 PM</td><td>10:48 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>10:50 PM</td><td ></td><td></td><td >10:51 PM</td><td></td><td >10:54 PM</td><td>10:56 PM</td><td ></td><td></td><td ></td><td></td><td >11:00 PM</td><td>11:03 PM</td><td >11:06 PM</td><td>11:08 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>11:10 PM</td><td ></td><td></td><td >11:11 PM</td><td></td><td >11:14 PM</td><td>11:16 PM</td><td ></td><td></td><td ></td><td></td><td >11:20 PM</td><td>11:23 PM</td><td >11:26 PM</td><td>11:28 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>11:30 PM</td><td ></td><td></td><td >11:31 PM</td><td></td><td >11:34 PM</td><td>11:36 PM</td><td ></td><td></td><td ></td><td></td><td >11:40 PM</td><td>11:43 PM</td><td >11:46 PM</td><td>11:48 PM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>11:50 PM</td><td ></td><td></td><td >11:51 PM</td><td></td><td >11:54 PM</td><td>11:56 PM</td><td ></td><td></td><td ></td><td></td><td >12:00 AM</td><td>12:02 AM</td><td >12:05 AM</td><td>12:07 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>12:10 AM</td><td ></td><td></td><td >12:11 AM</td><td></td><td >12:13 AM</td><td>12:15 AM</td><td ></td><td></td><td ></td><td></td><td >12:18 AM</td><td>12:20 AM</td><td >12:23 AM</td><td>12:25 AM</td></tr>
<tr><td></td><td ></td><td></td><td ></td><td></td><td ></td><td>12:30 AM</td><td ></td><td></td><td >12:31 AM</td><td></td><td >12:33 AM</td><td>12:35 AM</td><td ></td><td></td><td ></td><td></td><td >12:38 AM</td><td>12:40 AM</td><td >12:43 AM</td><td>12:45 AM</td></tr>
</table>

</body>
</html>